INSERT INTO projects
(projectName, projectType, url, github, img, video, description, keywords, ranking, created_at, 
updated_at)
VALUES
('Duh!Travel Planner!' , 'webdev', 'https://truslide12.github.io/Project1/' , 'https://github.com/Truslide12/Project1', 'DuhTravelplanner.png', 'DuhTravelplanner.png' , 'Travel planner app utilizing HTML, Javascript, googleMaps and eventBright APIs. Select the events you want from the list or from the map. It then stores your list in firebase or local storage to be printed out or viewed at a later date. ', 'html, firebase database, google maps, places, eventbright api, bootstrap', '4', CURRENT_TIME, CURRENT_TIME),
('Train Scheduler' , 'webdev', 'https://truslide12.github.io/TrainScheduler/', 'https://github.com/Truslide12/TrainScheduler' , 'TrainScheduler.png' , 'TrainScheduler.png' , 'A simple HTML/Javascript app that utilizes moment.js to calclulate the next expected train time arrival based on when the trains start and their regular arrival differentials', 'html, javascrip, moment.js, bootstrap, nodejs, express', '11', CURRENT_TIME, CURRENT_TIME),
('Harry Potter HangMan', 'webdev', 'https://github.com/Truslide12/wordguess', 'https://truslide12.github.io/wordguess/' , 'Harry Potter Hangman.png', 'Harry Potter Hangman.png' , 'HTML/Javascript app that allows you to play hangman and attempt to guess words.', 'html, javascript, bootstrap', '13', CURRENT_TIME, CURRENT_TIME),
('GifTastic' , 'webdev',  'https://truslide12.github.io/GifTastic/', 'https://github.com/Truslide12/GifTastic', 'GifTastic.png' , 'GifTastic.png' , 'HTML/Jacascript app using Giphy API to search for images', 'html, javascript, giphy api, bootstrap, nodejs, express', '14', CURRENT_TIME, CURRENT_TIME),
('Crystal Collector' , 'webdev', 'https://truslide12.github.io/crystalcollector/', 'https://github.com/Truslide12/crystalcollector' , 'Crystal Collector.png', 'Crystal Collector.png', 'A Javascript game where you attepmt to chose crystals with set values to obtain a randomly selected goal', 'html, javascript, bootstrap', '8', CURRENT_TIME, CURRENT_TIME),
('Star Wars Trivia' , 'webdev', 'https://truslide12.github.io/TriviaGame/' , 'https://github.com/Truslide12/StarWars-Express', 'StarWars Trivia.png' ,  'StarWars Trivia.png' , 'HTML Javascript game that presents the user with questions and a selcetion of answers. When the user clicks on an answer it stores the answer and loads a new question. When all questions have been answered the app calculates the user score', 'html, javascript, bootstrap', '14', CURRENT_TIME, CURRENT_TIME),
('LiriBot' , 'nodejs', 'https://truslide12.github.io/Liri/' , 'https://github.com/Truslide12/Liri', 'Screen Shot 2019-08-23 at 10.43.12 AM.png' , 'Screen Shot 2019-08-23 at 10.43.12 AM.png' , 'Command line application that searchs for song information from spotify, concert information from BandsinTown and movie information from OMBD','nodejs, express', '10', CURRENT_TIME, CURRENT_TIME),
('Bamazon' , 'nodejs', 'https://truslide12.github.io/NodeMySQL/', 'https://github.com/Truslide12/NodeMySQL',  'Screen Shot 2019-08-23 at 10.43.12 AM.png', 'Screen Shot 2019-08-23 at 10.43.12 AM.png' , 'command line nodejs, express app that uses mysql to store customer purchases, track/order inventory and calculate profit/loss', 'nodejs, express, mysql', '12', CURRENT_TIME, CURRENT_TIME),
('MyRolodex' , 'webdev', 'http://myrolodex.herokuapp.com/', 'https://truslide12.github.io/MyRolodex' , 'MyRolodex.png' , 'MyRolodex.png' , 'A PHP app that allows the user to save and edit their contacts with addresses and phone numbers', 'php, mysql, bootstrap', '1', CURRENT_TIME, CURRENT_TIME),
('BookFinder' , 'webdev', 'https://googlebooksearchcsa.herokuapp.com/', 'https://truslide12.github.io/Book-Finder' , 'googlebbokfinder.png' , 'googlebbokfinder.png' , 'Search and save books to read using google books api', 'reactjs, nodejs, mysql', '7', CURRENT_TIME, CURRENT_TIME),
('BeyondDjs' , 'webdev', 'https://beyonddjs.herokuapp.com/', 'https://github.com/Truslide12/BeyondDJs' , 'beyonddjs.png' , 'beyonddjs.png' , 'React app that allows people to find djs for their events and stores the evnets using MySQL', 'reactjs, html, mysql, bootstrap, nodejs, express', '3', CURRENT_TIME, CURRENT_TIME),
('Eat-A-Burger' , 'webdev', 'https://agile-scrubland-77250.herokuapp.com/', 'https://truslide12.github.io/Eat-A-Burger' , 'Eat-a-Burger.png' , 'Eat-a-Burger.png' ,'Express and mysql app that tracks create burgers and handle customer orders', 'html, javascript, mysql, bootstrap, nodejs, express', '6', CURRENT_TIME, CURRENT_TIME),
('DJSetList' , 'webdev', 'https://djsetlistgame.herokuapp.com/', 'https://truslide12.github.io/DJSetList---React-Game' , 'DjSetList.png' , 'DjSetList.png' , 'A react game that lets you create a dj set list for an event that calculates home much time for the event and subdtracts for each dj you select', 'html, javascript, mysql, bootstrap, nodejs, express, reactjs, react', '5', CURRENT_TIME, CURRENT_TIME),
('New Web Scrapper' , 'webdev', 'https://newswebscrapper21.herokuapp.com/', 'https://truslide12.github.io/News-Webscrapper' , 'NewsWebScrapper.png' , 'NewsWebScrapper.png' , 'A webscrapper api app to add and save your favorite articles', 'html, javascript, mysql, bootstrap, nodejs, express', '9', CURRENT_TIME, CURRENT_TIME),
('Rum Runner', 'webdev', 'https://piratetreasurehunter.herokuapp.com/', 'https://github.com/Truslide12/Project2', 'rumrunnerfrontpage.png', 'rumrunnerfrontpage.png', 'Fun 8-bit game using phaser 3, reactjs and express. Collect as many coins as your can!!!', 'html, javascript, reactjs, nodejs, express, mysql, phaser3, bootstrap', '2', CURRENT_TIME, CURRENT_TIME);